const products = [

/* =========================
   🛋️ HOME DECOR
========================= */
{
  id: "p1",
  title: "Modern Gold Bird Sculptures",
  price: "Check Latest Price on Amazon",
  rating: 4.7,
  image: "https://m.media-amazon.com/images/I/71SKqRaBtwL._AC_SL1500_.jpg",
  category: "decor",
  badge: "✨ Trending",
  short: "Elegant gold bird statues for modern luxury spaces.",
  description: "Elevate your home with these modern gold bird sculptures—perfect for styling shelves, coffee tables, or office desks. A minimalist yet luxurious accent that instantly makes your space feel designer-curated.",
  tags: ["gold decor", "bird figurine", "modern decor", "luxury home"],
  affiliate: "https://amzn.to/4tZ44BX"
},

{
  id: "2",
  title: "VASAGLE Round Coffee Table Set of 2",
  price: "Check Latest Price on Amazon",
  rating: 4.7,
  image: "https://m.media-amazon.com/images/I/71HwRjWEjuL._AC_SL1500_.jpg",
  category: "decor",
  badge: "✨ Bestseller",
  short: "Modern nesting coffee tables with sleek minimalist design.",
  description: "Stylish set of 2 round nesting coffee tables featuring a white tabletop and black steel frame. Includes a removable top for hidden storage—perfect for modern living rooms, apartments, and aesthetic home setups.",
  tags: ["coffee table", "nesting table", "living room", "modern decor", "minimalist", "home furniture"],
  affiliate: "https://amzn.to/4d2Xk0b"
},
{
  id: "p3",
  title: "Farmhouse Teal Cushion Covers Set of 4 (45x45 cm)",
  price: "Check Latest Price on Amazon",
  rating: 4.4,
  image: "https://m.media-amazon.com/images/I/71YUzdszBmL._AC_SL1500_.jpg",
  category: "decor",
  badge: "✨ Amazon Choice",
  short: "Elegant teal textured cushion covers for cozy modern interiors.",
  description: "Set of 4 farmhouse-style cushion covers in a 45x45 cm size. Designed with textured patchwork fabric in a stylish teal tone, perfect for sofas, beds, chairs, office spaces, and modern home styling. Adds a cozy, aesthetic upgrade to any room instantly.",
  tags: [
    "cushion covers",
    "pillow covers",
    "home decor",
    "sofa decor",
    "farmhouse style",
    "modern living room",
    "teal decor",
    "interior styling"
  ],
   affiliate: "https://amzn.to/3QXvPws"
},
{
  id: "p4",
  title: "Sunflower Paper Towel Holder – Farmhouse Kitchen Decor",
  price: "Check Latest Price on Amazon",
  rating: 4.4,
  image: "https://m.media-amazon.com/images/I/61EouKc6UrL._AC_SL1200_.jpg",
  category: "decor",
  badge: "🌻 Best Gift Idea",
  short: "Rustic sunflower paper towel holder for warm farmhouse kitchens.",
  description: "Beautiful sunflower-themed paper towel holder designed for farmhouse and rustic kitchen aesthetics. Made with durable black metal and detailed sunflower accents, it adds a cozy country charm to countertops. Perfect as a housewarming or gift item for kitchen lovers.",
  tags: [
    "kitchen decor",
    "paper towel holder",
    "farmhouse kitchen",
    "sunflower decor",
    "rustic home",
    "country style",
    "kitchen accessories",
    "gift idea"
  ],
  affiliate: "https://amzn.to/4sMaaod"
},
{
  id: "p5",
  title: "Modern Black & Gold 3-Light Bathroom Vanity Fixture with Glass Shades",
  price: "Check Latest Price on Amazon",
  rating: 4.6,
  image: "https://m.media-amazon.com/images/I/71V+5NXFouL._AC_SL1500_.jpg",
  category: "decor",
  badge: "✨ Luxury Upgrade",
  short: "Elegant black and gold vanity lighting for modern bathroom mirrors.",
  description: "Stylish 3-light bathroom vanity fixture featuring a modern black and brushed gold finish with square glass shades. Designed for installation over mirrors, it enhances bathrooms, bedrooms, and hallways with a warm, luxury hotel-style glow. Perfect for modern and contemporary home interiors.",
  tags: [
    "bathroom lighting",
    "vanity light",
    "wall sconce",
    "modern lighting",
    "bathroom decor",
    "luxury home",
    "gold fixtures",
    "mirror lighting"
  ],
   affiliate: "https://amzn.to/4mQg6eE"
},
{
  id: "p6",
  title: "Natural Rattan Fruit Basket Set (Set of 3)",
  price: "Check Latest Price on Amazon",
  rating: 4.7,
  image: "https://m.media-amazon.com/images/I/814L+W9ougL._AC_SL1500_.jpg",
  category: "decor",
  badge: "🌿 Bestseller",
  short: "Handwoven rattan baskets for stylish kitchen and dining organization.",
  description: "Upgrade your home with this beautifully handwoven natural rattan fruit basket set of 3. Perfect for storing fruits, bread, or serving essentials while adding a warm boho, farmhouse, or coastal aesthetic to your kitchen or dining space. A functional yet elegant décor piece designed for modern minimalist homes.",
  tags: ["rattan basket", "kitchen storage", "boho decor", "wicker organizer", "farmhouse kitchen"],
  affiliate: "https://amzn.to/4e2XXYL"
},
{
  "id": "potato-estudiosa-motivation",
  "title": "Potato Estudiosa® Student Motivation Gift",
  "price": "Check Latest Price on Amazon",
  "rating": 4.4,
  "image": "https://m.media-amazon.com/images/I/71GTkmeD8FL._AC_SL1500_.jpg",
  "category": "decor",
  "badge": "📚 Study Must-Have",
  "short": "Cute motivational potato decor for study desks.",
  "description": "Transform your study space into a focused, aesthetic zone with this adorable Potato Estudiosa® figurine. Designed to spark motivation and bring a smile during long study sessions, it's the perfect desk companion for students, teens, and exam warriors. A small detail that creates a big productivity vibe—ideal for aesthetic study setups and cozy desk styling.",
  "tags": ["study decor", "student gift", "desk aesthetic", "motivation decor", "study room ideas"],
  "affiliate": "https://amzn.to/3P5Yor3"
},
{
  "id": "mixed-beach-seashells-starfish-decor",
  "title": "Mixed Beach Seashells & Starfish Set (9 Types)",
  "price": "Check Latest Price on Amazon",
  "rating": 4.4,
  "image": "https://m.media-amazon.com/images/I/81ZRnZAoqgL._AC_SL1500_.jpg",
  "category": "decor",
  "badge": "🏖️ Summer Favorite",
  "short": "Natural seashells & starfish for coastal home styling.",
  "description": "Bring effortless coastal elegance into your space with this mixed seashell and starfish set. Featuring 9 varieties of natural shells, this collection is perfect for styling glass vases, coffee tables, or beach-themed decor. Instantly create that breezy, seaside vibe—whether you're decorating a summer apartment, hosting a coastal party, or curating a Pinterest-worthy shelf.",
  "tags": ["coastal decor", "beach house decor", "summer styling", "seashell decor", "vase fillers"],
  "affiliate": "https://amzn.to/4mP5Z9U"
},
{
  "id": "smuxee-nesting-coffee-table-set",
  "title": "Smuxee Nesting Coffee Table Set of 2",
  "price": "Check Latest Price on Amazon",
  "rating": 4.6,
  "image": "https://m.media-amazon.com/images/I/91EfC6N5JWL._AC_SL1500_.jpg",
  "category": "decor",
  "badge": "✨ Best Seller",
  "short": "Modern nesting coffee tables for stylish small spaces.",
  "description": "Upgrade your living room instantly with this elegant nesting coffee table set. Featuring warm wood-grain tops and sleek industrial metal frames, these round tables bring designer style without the designer price tag. Use them together for a layered luxury look or separately as side tables in apartments, bedrooms, balconies, or cozy reading corners. Perfect for modern, minimalist, and Pinterest-inspired interiors.",
  "tags": ["coffee table", "small living room decor", "modern furniture", "nesting table", "luxury apartment decor"],
  "affiliate": "https://amzn.to/4eNyMJV"
},
{
  "id": "aubcee-faux-pink-dahlia-vase",
  "title": "Aubcee Faux Pink Dahlia Flowers with Vase",
  "price": "Check Latest Price on Amazon",
  "rating": 4.6,
  "image": "https://m.media-amazon.com/images/I/81BQdMXAkoL._AC_SL1500_.jpg",
  "category": "decor",
  "badge": "🌸 Trending",
  "short": "Elegant pink faux flowers in vase for chic home styling.",
  "description": "Add instant softness and elegance to your space with these faux pink dahlia flowers in a decorative vase. Designed to look fresh year-round, this stylish arrangement brings a romantic, luxury feel to coffee tables, bathroom counters, entryways, and shelves. Perfect for creating that polished Pinterest home aesthetic without the upkeep of real flowers.",
  "tags": ["faux flowers", "pink decor", "coffee table decor", "feminine home decor", "luxury vase decor"],
  "affiliate": "https://amzn.to/4sZDSpV"
},
{
  "id": "nacome-solar-turtle-garden-statue",
  "title": "Nacome Solar Turtle Garden Statue with LED Lights",
  "price": "Check Latest Price on Amazon",
  "rating": 4.5,
  "image": "https://m.media-amazon.com/images/I/71Mq0xq6M4L._AC_SL1500_.jpg",
  "category": "decor",
  "badge": "🐢 #1 Best Seller",
  "short": "Whimsical solar turtle statue with glowing garden lights.",
  "description": "Bring charm and warmth to your outdoor space with this adorable solar turtle garden statue. Featuring a succulent-style shell and 7 soft LED lights, it automatically glows at night to create a magical garden atmosphere. Perfect for patios, balconies, porches, flower beds, or as a thoughtful gift for moms, grandmas, and nature lovers.",
  "tags": ["garden decor", "solar lights", "patio decor", "gift for mom", "outdoor statue"],
  "affiliate": "https://amzn.to/4d26nh0"
},
{
  "id": "asmad-solar-firefly-lights-4pack",
  "title": "ASMAD Solar Firefly Garden Lights (4 Pack)",
  "price": "Check Latest Price on Amazon",
  "rating": 4.5,
  "image": "https://m.media-amazon.com/images/I/815Gp83CG4L._AC_SL1500_.jpg",
  "category": "decor",
  "badge": "✨ Limited Time Deal",
  "short": "Magical swaying solar lights for dreamy outdoor spaces.",
  "description": "Transform your patio, garden, or balcony into an enchanting nighttime escape with these solar firefly lights. Featuring 32 warm LEDs and flexible stems that sway beautifully in the breeze, they create a whimsical glow that feels straight out of a luxury garden retreat. Perfect for pathways, flower beds, patios, and thoughtful gifts for moms or grandmas who love beautiful outdoor spaces.",
  "tags": ["solar lights", "garden decor", "patio lighting", "gift for grandma", "backyard ideas"],
  "affiliate": "https://amzn.to/48rhwq3"
},
{
  "id": "qocnam-solar-watering-can-lantern",
  "title": "QOCNAM Solar Watering Can Fairy Lantern",
  "price": "Check Latest Price on Amazon",
  "rating": 4.5,
  "image": "https://m.media-amazon.com/images/I/81DC8QbOm0L._AC_SL1500_.jpg",
  "category": "decor",
  "badge": "✨ Amazon's Choice",
  "short": "Enchanting solar watering can light for magical gardens.",
  "description": "Create a storybook glow in your outdoor space with this charming solar watering can lantern. Designed with cascading fairy lights and crackle glass detail, it looks like sparkling water pouring from the can after sunset. Perfect for patios, balconies, lawns, porches, and garden corners that need a whimsical designer touch. A beautiful gift idea for anyone who loves gardening and cozy evenings outdoors.",
  "tags": ["garden decor", "solar lantern", "patio lights", "gift for gardener", "outdoor decor"],
  "affiliate": "https://amzn.to/3P6kl9s"
},
{
  "id": "amdrebio-pink-round-fluffy-rug-4ft",
  "title": "Amdrebio Light Pink Round Fluffy Rug 4Ft",
  "price": "Check Latest Price on Amazon",
  "rating": 4.5,
  "image": "https://m.media-amazon.com/images/I/81doeAtY-bS._AC_SL1500_.jpg",
  "category": "decor",
  "badge": "💗 Amazon's Choice",
  "short": "Soft pink fluffy rug for dreamy bedrooms & dorms.",
  "description": "Add instant softness and charm to your space with this light pink round fluffy rug. Designed to create a cozy, stylish vibe, this plush shag rug is perfect for girls’ bedrooms, dorm rooms, nurseries, playrooms, or reading corners. The soft texture and sweet blush tone make any room feel warmer, prettier, and Pinterest-worthy in minutes.",
  "tags": ["pink room decor", "girls bedroom", "fluffy rug", "dorm decor", "cute room aesthetic"],
  "affiliate": "https://amzn.to/4uc8c1v"
},
{
  "id": "uvvyui-blue-velvet-shell-pillow",
  "title": "Uvvyui Blue Velvet Sea Shell Throw Pillow",
  "price": "Check Latest Price on Amazon",
  "rating": 4.5,
  "image": "https://m.media-amazon.com/images/I/71wKhH2fkML._AC_SL1500_.jpg",
  "category": "decor",
  "badge": "🌊 Amazon's Choice",
  "short": "Chic velvet shell pillow for coastal luxe spaces.",
  "description": "Bring elegant coastal charm into your home with this blue velvet sea shell shaped throw pillow. Featuring a plush cotton fill and rich velvet texture, it adds softness, style, and a designer touch to sofas, beds, accent chairs, or reading nooks. Perfect for beach-inspired interiors, feminine bedrooms, and modern spaces needing a unique statement accent.",
  "tags": ["coastal decor", "throw pillow", "beach room decor", "blue velvet pillow", "luxury home decor"],
  "affiliate": "https://amzn.to/49hCLuF"
},
{
  "id": "phantoscope-pink-faux-fur-pillow-covers",
  "title": "Phantoscope Pink Faux Fur Throw Pillow Covers (Set of 2)",
  "price": "Check Latest Price on Amazon",
  "rating": 4.6,
  "image": "https://m.media-amazon.com/images/I/81QDkoaSYrL._AC_SL1500_.jpg",
  "category": "decor",
  "badge": "💗 Cozy Favorite",
  "short": "Luxury faux fur pillow covers for chic cozy spaces.",
  "description": "Add instant softness and glamour to your home with these blush pink faux fur throw pillow covers. Designed to bring warmth, texture, and a luxurious cozy vibe, they’re perfect for beds, sofas, accent chairs, dorm rooms, or festive holiday styling. The plush fuzzy finish creates that designer layered look every stylish space needs.",
  "tags": ["pink pillow covers", "cozy decor", "bedroom aesthetic", "faux fur pillows", "luxury home decor"],
  "affiliate": "https://amzn.to/4f2I8S8"
},
{
  "id": "bignosedeer-kawaii-cat-tea-mug-infuser",
  "title": "BigNoseDeer Kawaii Cat Tea Cup with Infuser (13oz)",
  "price": "Check Latest Price on Amazon",
  "rating": 4.8,
  "image": "https://m.media-amazon.com/images/I/61Tb5j081mL._AC_SL1000_.jpg",
  "category": "decor",
  "badge": "🐱 Amazon's Choice",
  "short": "Cute pink cat mug with tea infuser for cozy drink moments.",
  "description": "Bring adorable charm to your daily tea or coffee routine with this kawaii cat tea mug. Featuring a built-in infuser and a soft pastel pink design, it’s perfect for brewing loose-leaf tea or enjoying cozy coffee moments. Ideal for cat lovers, aesthetic kitchen setups, dorm rooms, or thoughtful gifts for women who love cute, preppy-style essentials.",
  "tags": ["cute mug", "cat lover gift", "tea mug", "kawaii kitchen", "aesthetic drinkware"],
  "affiliate": "https://amzn.to/4mYZzFn"
},
{
  "id": "dcoriuntg-3d-crystal-ball-night-light",
  "title": "3D Crystal Ball Night Light with Remote (16 Colors)",
  "price": "Check Latest Price on Amazon",
  "rating": 4.4,
  "image": "https://m.media-amazon.com/images/I/8113ZAZqSiL._AC_SL1500_.jpg",
  "category": "decor",
  "badge": "🌙 Amazon's Choice",
  "short": "Color-changing crystal ball night light for magical room vibes.",
  "description": "Create a dreamy, glowing atmosphere with this 3D crystal ball night light featuring 16 color modes and remote control. The elegant glass sphere design casts soft ambient light, making it perfect for bedrooms, desks, bedside tables, or cozy aesthetic setups. Ideal for kids, teens, and adults who love magical, calming decor or unique gift ideas.",
  "tags": ["night light", "room decor", "LED lamp", "aesthetic lighting", "gift idea"],
  "affiliate": "https://amzn.to/4cRUt9j"
},
{
  "id": "nourison-passion-ivory-fuchsia-area-rug-7x10",
  "title": "Nourison Home Passion Ivory/Fuchsia Area Rug 7x10",
  "price": "Check Latest Price on Amazon",
  "rating": 4.6,
  "image": "https://m.media-amazon.com/images/I/91FTndISD4L._AC_SL1500_.jpg",
  "category": "decor",
  "badge": "✨ Amazon's Choice",
  "short": "Elegant ivory & fuchsia rug for vibrant modern interiors.",
  "description": "Transform any space instantly with this Nourison Passion area rug in ivory and fuchsia. Designed to blend modern elegance with bold color accents, it adds warmth, personality, and designer appeal to bedrooms, living rooms, dining areas, or apartments. The soft, easy-clean, non-shedding texture makes it both stylish and practical for everyday living while elevating your entire room aesthetic.",
  "tags": ["area rug", "living room decor", "modern home decor", "colorful rug", "apartment styling"],
  "affiliate": "https://amzn.to/4eOchVd"
},
{
  "id": "dovdov-handblown-glass-conch-sculpture-green",
  "title": "Hand-Blown Green Glass Conch Shell Sculpture",
  "price": "Check Latest Price on Amazon",
  "rating": 4.7,
  "image": "https://m.media-amazon.com/images/I/61Kgi-V5nDL._AC_SL1500_.jpg",
  "category": "decor",
  "badge": "🌊 Amazon's Choice",
  "short": "Elegant sea glass conch sculpture for coastal luxury decor.",
  "description": "Elevate your space with this hand-blown green glass conch sculpture, designed to bring a refined coastal elegance into modern interiors. Its smooth sea-glass finish and artistic shell form make it a striking statement piece for TV cabinets, coffee tables, office desks, and shelving displays. Perfect for creating a calm, ocean-inspired luxury aesthetic in any room.",
  "tags": ["coastal decor", "glass sculpture", "luxury home decor", "shell decor", "modern aesthetic"],
  "affiliate": "https://amzn.to/3QD1Xpc"
},
{
  "id": "wongs-boho-grey-floral-comforter-set",
  "title": "WONGS Bohemian Grey Floral Comforter Set (Queen)",
  "price": "Check Latest Price on Amazon",
  "rating": 4.6,
  "image": "https://m.media-amazon.com/images/I/91as647raBL._AC_SL1500_.jpg",
  "category": "decor",
  "badge": "🌿 Boho Favorite",
  "short": "Vintage floral boho bedding for cozy, aesthetic bedrooms.",
  "description": "Transform your bedroom into a cozy bohemian retreat with this grey floral patchwork comforter set by WONGS. Featuring a soft microfiber fabric and vintage-inspired striped floral design, it adds warmth, texture, and effortless style to your space. Perfect for creating that Pinterest-worthy boho bedroom aesthetic in apartments, guest rooms, or modern homes.",
  "tags": ["boho bedding", "floral bedroom", "vintage bedding", "bedroom aesthetic", "cozy decor"],
  "affiliate": "https://amzn.to/4w2i5Rh"
},
{
  "id": "wongs-boho-yellow-patchwork-comforter-set",
  "title": "WONGS Bohemian Yellow Floral Comforter Set (Queen)",
  "price": "Check Latest Price on Amazon",
  "rating": 4.6,
  "image": "https://m.media-amazon.com/images/I/81kBpIBoEEL._AC_SL1500_.jpg",
  "category": "decor",
  "badge": "🌞 Boho Cozy Favorite",
  "short": "Warm bohemian yellow bedding for cozy aesthetic bedrooms.",
  "description": "Brighten your bedroom instantly with this WONGS bohemian comforter set in a warm yellow floral patchwork design. Made with soft microfiber and paired with matching pillow shams, it creates a cozy, sunlit, Pinterest-worthy bedroom atmosphere. Perfect for apartments, guest rooms, or anyone wanting a cheerful boho aesthetic that feels both relaxed and stylish.",
  "tags": ["boho bedding", "yellow bedroom", "cozy decor", "floral bedding", "aesthetic bedroom"],
  "affiliate": "https://amzn.to/4n3NDCn"
},
{
  "id": "dfxsz-spring-summer-yellow-floral-pillow-covers",
  "title": "DFXSZ Spring Summer Yellow Floral Pillow Covers (Set of 2)",
  "price": "Check Latest Price on Amazon",
  "rating": 4.6,
  "image": "https://m.media-amazon.com/images/I/81sg2p2skmL._AC_SL1500_.jpg",
  "category": "decor",
  "badge": "🌼 Seasonal Favorite",
  "short": "Bright farmhouse floral pillow covers for spring/summer decor.",
  "description": "Refresh your home for the season with these cheerful DFXSZ farmhouse pillow covers featuring sunflower and floral heart designs in warm yellow tones. Soft plush faux fur jacquard texture adds cozy comfort while instantly brightening sofas, beds, and living spaces. Perfect for spring and summer home styling, farmhouse decor lovers, and seasonal room refreshes.",
  "tags": ["spring decor", "summer home decor", "farmhouse pillows", "sunflower decor", "cozy living room"],
  "affiliate": "https://amzn.to/3Phoc3B"
},
{
  "id": "releany-pink-vintage-medallion-area-rug-5x7",
  "title": "RELEANY Pink Vintage Medallion Area Rug 5x7 Washable",
  "price": "Check Latest Price on Amazon",
  "rating": 4.6,
  "image": "https://m.media-amazon.com/images/I/81XqHlWWIbL._AC_SL1500_.jpg",
  "category": "decor",
  "badge": "🌸 Amazon's Choice",
  "short": "Washable vintage floral rug for cozy pink aesthetic spaces.",
  "description": "Elevate your space instantly with this RELEANY vintage floral medallion area rug in soft pink and grey tones. Designed with a distressed print pattern, it brings a cozy, lived-in elegance to living rooms, bedrooms, dining areas, or apartments. The washable, non-slip design makes it both stylish and practical—perfect for creating a feminine, Pinterest-worthy home aesthetic.",
  "tags": ["pink rug", "vintage decor", "area rug", "home aesthetic", "cozy room decor"],
  "affiliate": "https://amzn.to/4tl13vi"
},
{
  "id": "crocon-amethyst-crystal-tree-of-life",
  "title": "Crocon Amethyst Crystal Tree of Life Decor Gift",
  "price": "Check Latest Price on Amazon",
  "rating": 4.6,
  "image": "https://m.media-amazon.com/images/I/81WPf6mWQzL._AC_SL1500_.jpg",
  "category": "decor",
  "badge": "💜 Gift Favorite",
  "short": "Elegant amethyst crystal tree for healing vibes & home decor.",
  "description": "Bring beauty and positive energy into any space with this Crocon Amethyst Crystal Tree of Life decor piece. Designed with sparkling amethyst-style stones and an artistic wire tree shape, it adds a calming, luxurious touch to desks, shelves, bedside tables, and meditation corners. A thoughtful gift idea for moms, sisters, friends, housewarmings, or anyone who loves meaningful decor.",
  "tags": ["crystal decor", "gift for mom", "spiritual decor", "amethyst tree", "home aesthetic"],
  "affiliate": "https://amzn.to/4tksJ3k"
},
{
  "id": "lifewit-perfume-organizer-clear-display-stand",
  "title": "Lifewit Clear Perfume Organizer Display Stand",
  "price": "Check Latest Price on Amazon",
  "rating": 4.6,
  "image": "https://m.media-amazon.com/images/I/7124+y43fpL._AC_SL1500_.jpg",
  "category": "decor",
  "badge": "✨ #1 Best Seller",
  "short": "Elegant clear display stand for perfumes & beauty storage.",
  "description": "Turn your vanity into a boutique-style beauty space with this Lifewit clear perfume organizer. Designed with tiered shelves for stylish visibility, it beautifully displays perfumes, skincare, makeup, or cologne while keeping counters neat and clutter-free. Perfect for vanities, bathroom counters, dressers, and clean girl aesthetic setups that feel polished and luxurious.",
  "tags": ["perfume organizer", "vanity decor", "makeup storage", "beauty organizer", "clean girl aesthetic"],
  "affiliate": "https://amzn.to/4dc8MWs"
},
   

/* =========================
   ⚡ GADGETS
========================= */
{
  id: "p7",
  title: "Coway Airmega AP-1512HH(W) Air Purifier",
  price: "Check Latest Price on Amazon",
  rating: 4.6,
  image: "https://m.media-amazon.com/images/I/61Cgh4ol4oL._AC_SL1500_.jpg",
  category: "gadgets",
  badge: "🔥 Best Seller",
  short: "True HEPA air purifier with smart air quality monitoring.",
  description: "The Coway Airmega AP-1512HH(W) is a powerful True HEPA air purifier designed to improve indoor air quality. It features real-time air monitoring, auto mode, timer, filter indicator, and eco mode for energy efficiency. Ideal for modern homes seeking clean, fresh air.",
  tags: ["air purifier", "Coway", "HEPA filter", "home gadget", "clean air"],
  affiliate: "https://amzn.to/3Qop1b4"
},

{
  id: "p8",
  title: "Portable Foldable Neck Fan – Rechargeable 1600mAh",
  price: "Check Latest Price on Amazon",
  rating: 4.7,
  image: "https://ae-pic-a1.aliexpress-media.com/kf/S23fb5c6997334ab9a3dd60dfcc8f985bg.jpg_220x220q75.jpg_.avif",
  category: "gadgets",
  badge: "🔥 Best Seller",
  short: "Hands-free cooling neck fan for summer comfort & outdoor sports.",
  description: "Portable foldable neck fan with powerful 1600mAh rechargeable battery. Designed for hands-free cooling during sports, travel, commuting, and hot summer days. Lightweight, silent airflow, and modern wearable design.",
  tags: [
    "neck fan",
    "portable fan",
    "summer gadget",
    "cooling device",
    "rechargeable fan",
    "travel gadget",
    "sports accessories"
  ],
  affiliate: "https://s.click.aliexpress.com/e/_c3gyTc6f"
 
},
{
  id: "p9",
  title: "Smart Coffee Mug Warmer with Auto Shut Off – Desk Heater Plate",
  price: "Check Latest Price on Amazon",
  rating: 4.6,
  image: "https://m.media-amazon.com/images/I/71sTNNKjANL._AC_SL1500_.jpg",
  category: "gadgets",
  badge: "☕ Amazon’s Choice",
  short: "Keep your coffee, tea, or milk warm all day at your desk.",
  description: "Smart coffee mug warmer with adjustable temperature settings and auto shut-off safety feature. Designed for desks, offices, and home use. Works with most cups and mugs, also doubles as a candle wax warmer. Perfect for work-from-home comfort and cozy productivity.",
  tags: [
    "coffee mug warmer",
    "desk gadget",
    "home office",
    "coffee accessories",
    "tea warmer",
    "work from home",
    "gift idea",
    "kitchen gadget"
  ],
  affiliate: "https://amzn.to/3QZ7Ug7"
},
   {
  id: "p10",
  title: "Ultenic 3-in-1 Robot Vacuum & Mop with LiDAR Navigation",
  price: "Check Latest Price on Amazon",
  rating: 4.7,
  image: "https://m.media-amazon.com/images/I/81TDmHmWJbL._AC_SL1500_.jpg",
  category: "gadgets",
  badge: "🤖 Smart Home Upgrade",
  short: "Automatic robot vacuum & mop with powerful 8000Pa suction.",
  description: "Advanced 3-in-1 robot vacuum cleaner with sweeping, vacuuming, and mopping functions. Features 8000Pa suction power, 200-minute runtime, and precision LiDAR navigation for smart mapping. Supports multiple floor maps, no-go zones, and app control. Ideal for carpets, hard floors, and pet hair cleaning.",
  tags: [
    "robot vacuum",
    "smart home",
    "floor cleaner",
    "mop robot",
    "pet hair cleaner",
    "home automation",
    "cleaning gadget",
    "AI vacuum"
  ],
  affiliate: "https://amzn.to/4eFygxy"
},
{
  id: "p11",
  title: "Fullstar 6-in-1 Vegetable Chopper & Mandoline Slicer",
  price: "Check Latest Price on Amazon",
  rating: 4.4,
  image: "https://m.media-amazon.com/images/I/81ViXXJKNhL._AC_SL1500_.jpg",
  category: "gadgets",
  badge: "🔥 Amazon’s Choice",
  short: "Fast 6-in-1 vegetable chopper for effortless meal prep.",
  description: "Compact 6-in-1 vegetable chopper and mandoline slicer designed for quick and easy food preparation. Includes dicing, slicing, julienne cutting, and grating functions. Perfect for onions, cucumbers, tomatoes, potatoes, cheese, and salads. Makes cooking faster, cleaner, and more efficient.",
  tags: [
    "vegetable chopper",
    "kitchen gadget",
    "mandoline slicer",
    "food prep tool",
    "salad cutter",
    "onion chopper",
    "kitchen accessories",
    "meal prep"
  ],
 
  affiliate: "https://amzn.to/4u1NPnK"
},
{
  id: "12",
  title: "AMACOOL Portable Waist Clip-On Fan (10000mAh Rechargeable)",
  price: "Check Latest Price on Amazon",
  rating: 4.6,
  image: "https://m.media-amazon.com/images/I/61SQgVl99eL._AC_SL1500_.jpg",
  category: "gadgets",
  badge: "❄️ Amazon’s Choice",
  short: "Powerful wearable waist fan for cooling comfort on the go.",
  description: "Stay cool anywhere with the AMACOOL Portable Waist Clip-On Fan featuring a powerful 10000mAh rechargeable battery. Designed for hands-free cooling, it easily clips onto your belt or shirt—perfect for outdoor work, travel, camping, hiking, or hot summer days. A must-have personal cooling gadget for men and women who need strong airflow on the move.",
  tags: ["portable fan", "waist fan", "rechargeable fan", "summer gadget", "outdoor cooling", "travel essentials"],
  affiliate: "https://amzn.to/3P0qQdV"
},
{
  "id": "nespresso-vertuo-next-breville-frother",
  "title": "Nespresso Vertuo Next Coffee & Espresso Maker with Frother",
  "price": "Check Latest Price on Amazon",
  "rating": 4.3,
  "image": "https://m.media-amazon.com/images/I/71DDe-wo6wL._AC_SL1500_.jpg",
  "category": "gadgets",
  "badge": "☕ Amazon's Choice",
  "short": "Barista-style coffee at home with milk frother included.",
  "description": "Turn your kitchen into a chic café with the Nespresso Vertuo Next by Breville. This sleek machine brews rich coffee and smooth espresso at the touch of a button, while the included Aeroccino milk frother creates creamy lattes, cappuccinos, and iced coffee drinks at home. Perfect for busy mornings, apartment kitchens, and anyone who wants luxury coffee moments without leaving home.",
  "tags": ["coffee maker", "nespresso machine", "espresso maker", "kitchen upgrade", "home cafe"],
  "affiliate": "https://amzn.to/4cVOH6y"
},
{
  "id": "qpey-stainless-steel-onion-holder-slicer",
  "title": "Stainless Steel Onion Holder & Vegetable Slicer Tool",
  "price": "Check Latest Price on Amazon",
  "rating": 4.6,
  "image": "https://m.media-amazon.com/images/I/71GTPDTsoPL._AC_SL1500_.jpg",
  "category": "gadgets",
  "badge": "🔪 Amazon's Choice",
  "short": "Safe slicing tool for onions, tomatoes, eggs & veggies.",
  "description": "Make meal prep faster, safer, and more precise with this stainless steel onion holder slicer. Designed to firmly grip onions, tomatoes, avocados, eggs, and other vegetables, it helps you achieve even cuts while protecting your fingers. A must-have kitchen tool for home cooks who want efficiency, cleanliness, and professional-looking slices in seconds.",
  "tags": ["kitchen gadget", "onion slicer", "cooking tools", "meal prep", "kitchen hacks"],
  "affiliate": "https://amzn.to/4t8Tzep"
},
{
  "id": "owkar-portable-handheld-vacuum-sealer-kit",
  "title": "Portable Handheld Food Vacuum Sealer (32 Reusable Bags)",
  "price": "Check Latest Price on Amazon",
  "rating": 4.5,
  "image": "https://m.media-amazon.com/images/I/81qZCY1PGiL._AC_SL1500_.jpg",
  "category": "gadgets",
  "badge": "🥡 Amazon's Choice",
  "short": "Compact vacuum sealer for fresher food & meal prep storage.",
  "description": "Keep your food fresher for longer with this portable handheld vacuum sealer. Designed with a powerful suction system and visible liquid tank, it locks in freshness up to 6x longer while reducing food waste. Perfect for meal prep, fridge organization, leftovers, snacks, and travel storage. Includes reusable bags for an eco-friendly, budget-saving kitchen upgrade.",
  "tags": ["food storage", "kitchen gadget", "meal prep", "food saver", "kitchen organization"],
  "affiliate": "https://amzn.to/4cVt9ag"
},
{
  "id": "vaydeer-m4-mouse-mover-device",
  "title": "VAYDEER M4 Undetectable Mouse Motion Device",
  "price": "Check Latest Price on Amazon",
  "rating": 4.6,
  "image": "https://m.media-amazon.com/images/I/718MR7D1T9L._AC_SL1500_.jpg",
  "category": "gadgets",
  "badge": "⚡ Amazon's Choice",
  "short": "Auto mouse mover device for active screen & productivity support.",
  "description": "Keep your computer active effortlessly with the VAYDEER M4 Mouse Motion Device. Designed with a quiet motor and simple on/off switch, it simulates natural mouse movement to prevent screen sleep during work sessions, meetings, or long downloads. Compact and easy to use, it's a popular productivity tool for remote workers, office setups, and multitasking professionals.",
  "tags": ["productivity tool", "work from home", "tech gadget", "office setup", "computer accessory"],
  "affiliate": "https://amzn.to/3ODhaGd"
},
{
  "id": "biib-multifunction-led-pen-gift",
  "title": "BIIB Multifunction LED Tactical Pen (Gift for Men)",
  "price": "Check Latest Price on Amazon",
  "rating": 4.5,
  "image": "https://m.media-amazon.com/images/I/71cN-yH7HQL._AC_SL1500_.jpg",
  "category": "gadgets",
  "badge": "🎁 Top Gift Pick",
  "short": "Multifunction LED pen tool for everyday carry & gifting.",
  "description": "Give a practical and stylish gift with the BIIB multifunction LED tactical pen. Designed for everyday carry, it combines writing, lighting, and utility features in one compact tool. Perfect for Father’s Day, birthdays, camping trips, or office use, this gadget-style pen is both functional and impressive—making it a memorable gift for men who love smart tools.",
  "tags": ["men gift", "father's day gift", "tactical pen", "EDC gadget", "camping tool"],
  "affiliate": "https://amzn.to/4eUrx2R"
},
{
  "id": "trendplain-glass-olive-oil-sprayer-16oz",
  "title": "TrendPlain Glass Olive Oil Sprayer 2-in-1 Dispenser (470ml)",
  "price": "Check Latest Price on Amazon",
  "rating": 4.6,
  "image": "https://m.media-amazon.com/images/I/716HuBmcRsL._AC_SL1500_.jpg",
  "category": "gadgets",
  "badge": "🫒 #1 Best Seller",
  "short": "Healthy oil control sprayer for cooking, BBQ & air fryer use.",
  "description": "Upgrade your cooking routine with this sleek 2-in-1 glass olive oil sprayer. Designed for precision control, it lets you spray or pour oil evenly for air frying, salads, grilling, and everyday cooking. The modern black design fits perfectly in any kitchen aesthetic while helping reduce oil usage for a healthier lifestyle.",
  "tags": ["olive oil sprayer", "kitchen gadget", "air fryer accessory", "healthy cooking", "meal prep tools"],
  "affiliate": "https://amzn.to/4tPA9wz"
},
{
  "id": "pidinuk-magnetic-selfie-light-magsafe",
  "title": "PIDINUK Magnetic Selfie Light for iPhone MagSafe",
  "price": "Check Latest Price on Amazon",
  "rating": 4.6,
  "image": "https://m.media-amazon.com/images/I/61zvqZ9ZoYL._AC_SL1000_.jpg",
  "category": "gadgets",
  "badge": "✨ Amazon's Choice",
  "short": "Portable MagSafe selfie light for flawless photos & videos.",
  "description": "Level up your content instantly with this magnetic selfie light designed for MagSafe-compatible iPhones. Featuring rechargeable LED brightness, a built-in mirror, 5 adjustable color temperatures, and a foldable ring light design, it helps you capture clear, flattering photos and videos anywhere. Perfect for TikTok, Instagram, Zoom calls, makeup touch-ups, and on-the-go creators.",
  "tags": ["selfie light", "iphone accessory", "content creator", "ring light", "phone gadget"],
  "affiliate": "https://amzn.to/3Ppiug5"
},
{
  "id": "portable-mini-foldable-cleaning-mop",
  "title": "Portable Mini Foldable Cleaning Mop",
  "price": "Check Latest Price",
  "rating": 4.9,
  "image": "https://ae-pic-a1.aliexpress-media.com/kf/S3adcd64937234010b7cc98d8f56100b3C.jpg_220x220q75.jpg_.avif",
  "category": "gadgets",
  "badge": "🧼 Viral Cleaning Find",
  "short": "Compact foldable mini mop for quick mess cleanups anywhere.",
  "description": "Make everyday cleaning faster and easier with this portable mini foldable mop. Designed for desktops, kitchen counters, bathroom surfaces, mirrors, glass, living rooms, and even car interiors, it tackles spills and dust in seconds. Lightweight, space-saving, and easy to store, it’s the smart cleaning tool every organized home needs.",
  "tags": ["cleaning gadget", "mini mop", "home hacks", "kitchen cleaning", "viral products"],
  "affiliate": "https://s.click.aliexpress.com/e/_c4kw49Ix"
},
{
  "id": "yunzii-c75-cake-wireless-mechanical-keyboard",
  "title": "YUNZII C75 Wireless Mechanical Keyboard - Cute Cake Design",
  "price": "Check Latest Price on Amazon",
  "rating": 4.8,
  "image": "https://m.media-amazon.com/images/I/81QEYhLu80L._AC_SL1500_.jpg",
  "category": "gadgets",
  "badge": "⌨️ Amazon's Choice",
  "short": "Cute wireless mechanical keyboard for stylish desks & gaming.",
  "description": "Upgrade your desk setup with the YUNZII C75 wireless mechanical keyboard featuring an adorable cake-inspired design and premium typing feel. With Bluetooth, 2.4G, and USB-C connectivity, RGB lighting, hot-swappable switches, and soft MOA keycaps, it blends performance with personality. Perfect for gamers, students, creators, and anyone building a dreamy aesthetic workspace.",
  "tags": ["mechanical keyboard", "desk setup", "gaming keyboard", "cute tech", "wireless keyboard"],
  "affiliate": "https://amzn.to/42Vvzkk"
}
   
];
